/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import cjb.ci.Mensajes;

/**
 *
 * @author Meche}
 */
public class clienteRegistrado extends javax.swing.JFrame
{

    /**
     * Creates new form clienteRegistrado
     */
    public clienteRegistrado()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        numCliente = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        formaPago = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente registrado");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numCliente.setEnabled(false);
        getContentPane().add(numCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, -1));

        nombre.setEnabled(false);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, -1));

        fecha.setEnabled(false);
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 250, -1));

        formaPago.setEnabled(false);
        getContentPane().add(formaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/clienteRegistrado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        if (VtnPrincipal.tmpCliente != null)
        {
            numCliente.setText(String.valueOf(VtnPrincipal.tmpCliente.getFolioCliente()));
            nombre.setText(VtnPrincipal.tmpCliente.getNom());
            fecha.setText(VtnPrincipal.tmpCliente.getFecha());
            char formaPagoChar = VtnPrincipal.tmpCliente.getFormaPago();
            String formaPagoTexto;
            if (formaPagoChar == 'E')
            {
                formaPagoTexto = "Efectivo";
            } else if (formaPagoChar == 'T')
            {
                formaPagoTexto = "Tarjeta";
            } else
            {
                formaPagoTexto = "Desconocido";
            }
            formaPago.setText(formaPagoTexto);
        } else
        {
            Mensajes.error(this, "No se encontraron datos del cliente.");
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        new VtnRegistroCliente().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(clienteRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new clienteRegistrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField formaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numCliente;
    // End of variables declaration//GEN-END:variables
}
