/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import cjb.ci.Mensajes;
import poo.ManipulaArchivos;
import poo.Manipulacion;
import static poo.Manipulacion.buscarStatus;
import poo.Viaje;

/**
 *
 * @author Meche}
 */
public class VtnClienteDashboard extends javax.swing.JFrame
{

    public static int y = 0, pos2 = 0;
    public static double monto = 0;

    /**
     * Creates new form VtnClienteRegistrado
     */
    public VtnClienteDashboard()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnSolicitaViaje = new javax.swing.JToggleButton();
        btnCancelaViaje = new javax.swing.JToggleButton();
        btnConsultaViajes = new javax.swing.JToggleButton();
        btnConsultaGastos = new javax.swing.JToggleButton();
        btnReasignar = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSolicitaViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/iconoClienteSolicitaViaje.png"))); // NOI18N
        btnSolicitaViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitaViaje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSolicitaViajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btnCancelaViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/ClienteCancelaViaje.png"))); // NOI18N
        btnCancelaViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelaViaje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelaViajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        btnConsultaViajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/CllienteConsultaViajes.png"))); // NOI18N
        btnConsultaViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaViajes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConsultaViajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        btnConsultaGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/ClientesConsultaGastos.png"))); // NOI18N
        btnConsultaGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaGastos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConsultaGastosActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        btnReasignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/ClientesReasignar.png"))); // NOI18N
        btnReasignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReasignar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReasignarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReasignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/DashboardCliente.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalirActionPerformed
    {//GEN-HEADEREND:event_btnSalirActionPerformed
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVAC(VtnPrincipal.vC, "ViajesC.dat");

        VtnPrincipal vtn = new VtnPrincipal();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultaViajesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConsultaViajesActionPerformed
    {//GEN-HEADEREND:event_btnConsultaViajesActionPerformed
        vtnClienteConsultaViajes vtn = new vtnClienteConsultaViajes();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaViajesActionPerformed

    private void btnConsultaGastosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConsultaGastosActionPerformed
    {//GEN-HEADEREND:event_btnConsultaGastosActionPerformed
        vtnClientesConsultaGastos vtn = new vtnClientesConsultaGastos();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaGastosActionPerformed

    private void btnCancelaViajeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelaViajeActionPerformed
    {//GEN-HEADEREND:event_btnCancelaViajeActionPerformed
        if (VtnPrincipal.vC != null)
        {

            VtnPrincipal.tmpVC = Manipulacion.copiarViaje(VtnPrincipal.vC, Integer.parseInt(VtnCliente.fC));
            if (VtnPrincipal.tmpVC != null)
            {
                if (VtnPrincipal.tmpVC.getStatus() == 'E')
                {
                    if (VtnPrincipal.v != null)
                    {
                        VtnPrincipal.v = Manipulacion.cancelarViaje(VtnPrincipal.s, VtnPrincipal.vC,
                                Manipulacion.buscarStatusE(VtnPrincipal.vC, VtnPrincipal.s, VtnCliente.fC));
                        vtnViajeCancelado vtn = new vtnViajeCancelado();
                        vtn.setVisible(true);
                        this.setVisible(false);
                    }
                } else
                {
                    VtnPrincipal.vC = Manipulacion.cancelarViaje(VtnPrincipal.s, VtnPrincipal.vC, Manipulacion.buscarStatusE(VtnPrincipal.vC, VtnPrincipal.s, VtnCliente.fC));
                    vtnViajeCancelado vtn = new vtnViajeCancelado();
                    vtn.setVisible(true);
                    this.setVisible(false);
                }

            } else
            {
                Mensajes.error(this, "No hay viajes por cancelar");
            }

        } else
        {
            Mensajes.error(this, "No hay viajes por cancelar");
        }


    }//GEN-LAST:event_btnCancelaViajeActionPerformed

    private void btnSolicitaViajeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSolicitaViajeActionPerformed
    {//GEN-HEADEREND:event_btnSolicitaViajeActionPerformed
        int statusX = 0;
        if (VtnPrincipal.vC != null)
        {
            statusX = Manipulacion.buscarStatusEspera(VtnPrincipal.vC, VtnPrincipal.s, VtnCliente.fC);
        } else
        {
            statusX = 1;
        }
        switch (statusX)
        {
            case -1:
                Mensajes.error(this, "Ya tienes un viaje en espera");
                break;
            case 1:
                VtnSolicitarViaje vtn = new VtnSolicitarViaje();
                vtn.setVisible(true);
                this.setVisible(false);

                break;
        }

    }//GEN-LAST:event_btnSolicitaViajeActionPerformed

    private void btnReasignarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReasignarActionPerformed
    {//GEN-HEADEREND:event_btnReasignarActionPerformed
        int r = 0;
        if (VtnPrincipal.vC != null)
        {
            if (VtnPrincipal.s != null)
            {
                VtnPrincipal.tmpVC = Manipulacion.copiarViaje(VtnPrincipal.vC, Integer.parseInt(VtnCliente.fC));
                
                if (VtnPrincipal.tmpVC != null)
                {
                    pos2 = (int) (Math.random() * VtnPrincipal.s.length);
                    System.out.println(pos2 + " socio disponible");
                    r = Manipulacion.buscarStatusEspera3(VtnPrincipal.v, VtnPrincipal.s, pos2);
                    System.out.println(r);
                    switch (r)
                    {
                        case 1:
                            if (VtnPrincipal.tmpVC.getStatus() == 'E')
                            {

                                y = Manipulacion.buscarStatusEspera2(VtnPrincipal.v, VtnPrincipal.s, VtnCliente.fC);
                                VtnPrincipal.v = Manipulacion.elimina(VtnPrincipal.v, y, VtnCliente.fC);

                            }

                            if (pos2 >= 0)
                            {
                                Mensajes.exito(this, "Reasignando con: \n" + Manipulacion.despS2(VtnPrincipal.s, pos2));
                                VtnPrincipal.tmpVC.setStatus('E');
                                VtnPrincipal.v = Manipulacion.insertaViaje(VtnPrincipal.s, VtnPrincipal.v, VtnPrincipal.tmpVC, pos2);
                                System.out.println(Manipulacion.despV(VtnPrincipal.v, String.valueOf(pos2 - 1) + "Objeto en v"));

                            } else
                            {
                                Mensajes.error(this, "Aun no hay socios disponibles");

                            }
                            break;
                        case -1:
                            Mensajes.error(this, "no hay viajes en espera");
                            break;
                    }

                } else
                {
                    Mensajes.error(this, "no hay viajes en espera");
                }

            }else 
            {
                Mensajes.error(this, "no hay socios "); 
            }

        } else
        {
            Mensajes.error(this, "no hay viajes en espera");
        }
    }//GEN-LAST:event_btnReasignarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVAC(VtnPrincipal.vC, "ViajesC.dat");
        VtnPrincipal vtn = new VtnPrincipal();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        VtnPrincipal.v = (Viaje[][]) ManipulaArchivos.cargaAV("Viajes.dat");
        VtnPrincipal.vC = (Viaje[][]) ManipulaArchivos.cargaAVC("ViajesC.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVAC(VtnPrincipal.vC, "ViajesC.dat");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnClienteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnClienteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnClienteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnClienteDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnClienteDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelaViaje;
    private javax.swing.JToggleButton btnConsultaGastos;
    private javax.swing.JToggleButton btnConsultaViajes;
    private javax.swing.JToggleButton btnReasignar;
    private javax.swing.JToggleButton btnSalir;
    private javax.swing.JToggleButton btnSolicitaViaje;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
