/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import poo.Manipulacion;

/**
 *
 * @author Meche}
 */
public class VtnCliente extends javax.swing.JFrame
{

    public static String fC = " ", nom = " ";

    /**
     * Creates new form VtnCliente
     */
    public VtnCliente()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BtnCancelar = new javax.swing.JToggleButton();
        BtnRegistrarCliente = new javax.swing.JToggleButton();
        txtNumCliente = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCancelar.setBackground(new java.awt.Color(255, 115, 115));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Cancelar.png"))); // NOI18N
        BtnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        BtnRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/BtnRegitrarCliente.png"))); // NOI18N
        BtnRegistrarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnRegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        txtNumCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNumClienteActionPerformed(evt);
            }
        });
        txtNumCliente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNumClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNumClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 280, -1));

        btnAceptar.setBackground(new java.awt.Color(151, 247, 185));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Aceptar.png"))); // NOI18N
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/LoginCliente.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        new VtnPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void BtnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnRegistrarClienteActionPerformed
    {//GEN-HEADEREND:event_BtnRegistrarClienteActionPerformed
        VtnRegistroCliente vtnRegistrarCliente = new VtnRegistroCliente();
        vtnRegistrarCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegistrarClienteActionPerformed

    private void txtNumClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNumClienteActionPerformed
    {//GEN-HEADEREND:event_txtNumClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumClienteActionPerformed

    private void txtNumClienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNumClienteKeyPressed
    {//GEN-HEADEREND:event_txtNumClienteKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, txtNumCliente, btnAceptar);
    }//GEN-LAST:event_txtNumClienteKeyPressed

    private void txtNumClienteKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNumClienteKeyTyped
    {//GEN-HEADEREND:event_txtNumClienteKeyTyped
        Validaciones.validaEntero(evt, 5, txtNumCliente.getText());
    }//GEN-LAST:event_txtNumClienteKeyTyped

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnCancelarActionPerformed
    {//GEN-HEADEREND:event_BtnCancelarActionPerformed
        CtrlInterfaz.limpia(txtNumCliente);
        CtrlInterfaz.habilita(false, btnAceptar);
        CtrlInterfaz.selecciona(txtNumCliente);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        fC = txtNumCliente.getText();
        nom = Manipulacion.buscarClienteN(VtnPrincipal.c, Manipulacion.buscarCliente(VtnPrincipal.c, fC));
        if (nom == "nul")
        {
            Mensajes.exito(this, "usuario no encontrado");
        } else
        {
            new VtnClienteDashboard().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar()== '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnCancelar;
    private javax.swing.JToggleButton BtnRegistrarCliente;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumCliente;
    // End of variables declaration//GEN-END:variables
}
