/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import poo.Cliente;
import poo.ManipulaArchivos;
import poo.Socio;
import poo.Viaje;

/**
 *
 * @author Meche}
 */
public class VtnPrincipal extends javax.swing.JFrame
{
    public static Socio s[]=null;
    public static Cliente c[]=null;
    public static Viaje v[][]=null;
    public static Viaje vC[][]=null;
    public static Viaje tmpVC=null;
    
    public static Socio tmpSocio;

    /**
     * Creates new form VtnPrincipal
     */
    public VtnPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToggleButtonSocio = new javax.swing.JToggleButton();
        jToggleButtoncliente = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        VtnPrincipalBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movix");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButtonSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/iconoConductor.png"))); // NOI18N
        jToggleButtonSocio.setToolTipText("Socio");
        jToggleButtonSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtonSocio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jToggleButtonSocio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonSocioActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jToggleButtoncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/iconoPasaj.png"))); // NOI18N
        jToggleButtoncliente.setToolTipText("Cliente");
        jToggleButtoncliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButtoncliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButtonclienteActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtoncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Salir2.png"))); // NOI18N
        jToggleButton1.setToolTipText("Salir");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        VtnPrincipalBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/inicio.png"))); // NOI18N
        VtnPrincipalBackground.setToolTipText("");
        getContentPane().add(VtnPrincipalBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonSocioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButtonSocioActionPerformed
    {//GEN-HEADEREND:event_jToggleButtonSocioActionPerformed

        VtnSocio vtnLoginsocio = new VtnSocio();
        vtnLoginsocio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButtonSocioActionPerformed

    private void jToggleButtonclienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButtonclienteActionPerformed
    {//GEN-HEADEREND:event_jToggleButtonclienteActionPerformed
        VtnCliente vtnLoginCliente = new VtnCliente();
        vtnLoginCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButtonclienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
       s = (Socio[]) ManipulaArchivos.cargaAS("Socios.dat");
        try
        {
            Socio.setCons((int) ManipulaArchivos.cargaS("foliosS.dat"));
        } catch (Exception e)
        {
            Socio.setCons(0);
        }
       c = (Cliente[]) ManipulaArchivos.cargaAC("Clientes.dat");
        try
        {
            Socio.setCons((int) ManipulaArchivos.cargaC("foliosC.dat"));
        } catch (Exception e)
        {
            Socio.setCons(0);
        }
       v = (Viaje[][]) ManipulaArchivos.cargaAV("Viajes.dat");
       vC = (Viaje[][]) ManipulaArchivos.cargaAVC("ViajesC.dat");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        /*ManipulaArchivos.guardaCA(c, "cliente.dat");
        ManipulaArchivos.guarda(s, "socio.dat");
        ManipulaArchivos.guarda(v, "viajes.dat");
        ManipulaArchivos.guarda(Cliente.getCons(), "numCliente.dat");
        ManipulaArchivos.guarda(Socio.getCons(), "folios.dat");
        
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.vC, "ViajesC.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVAC(VtnPrincipal.vC, "ViajesC.dat");*/
        
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton1ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VtnPrincipalBackground;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButtonSocio;
    private javax.swing.JToggleButton jToggleButtoncliente;
    // End of variables declaration//GEN-END:variables
}
