/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import static Interfaz.VtnPrincipal.c;
import cjb.ci.BtnEntero;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import javax.swing.JOptionPane;
import poo.Cliente;
import poo.ManipulaArchivos;
import poo.Manipulacion;
import poo.Socio;

/**
 *
 * @author Meche}
 */
public class VtnRegistroCliente extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRegistroCliente
     */
    public VtnRegistroCliente()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        formaPago = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JToggleButton();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setToolTipText("Nombre del cliente");
        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, -1));

        txtFecha.setToolTipText("Fecha de registro");
        txtFecha.setEnabled(false);
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtFechaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtFechaKeyTyped(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, -1));

        formaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecciona-", "Tarjeta", "Efectivo" }));
        formaPago.setToolTipText("Forma de pago");
        formaPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        formaPago.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                formaPagoActionPerformed(evt);
            }
        });
        formaPago.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                formaPagoKeyPressed(evt);
            }
        });
        getContentPane().add(formaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 260, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 115, 115));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(151, 247, 185));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Aceptar.png"))); // NOI18N
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/RegistroClientes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyPressed
    {//GEN-HEADEREND:event_txtNombreKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, txtNombre, txtFecha);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFechaKeyPressed
    {//GEN-HEADEREND:event_txtFechaKeyPressed

        Validaciones.enterCadenaNoVacia(this, evt, txtFecha, btnAceptar);

    }//GEN-LAST:event_txtFechaKeyPressed

    private void formaPagoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_formaPagoActionPerformed
    {//GEN-HEADEREND:event_formaPagoActionPerformed

    }//GEN-LAST:event_formaPagoActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyTyped
    {//GEN-HEADEREND:event_txtNombreKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, txtNombre.getText());
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFechaKeyTyped
    {//GEN-HEADEREND:event_txtFechaKeyTyped
        Validaciones.validaFecha(evt, txtFecha.getText());
    }//GEN-LAST:event_txtFechaKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        CtrlInterfaz.limpia(txtNombre, txtFecha);
        CtrlInterfaz.habilita(false, txtFecha, btnAceptar);
        CtrlInterfaz.selecciona(txtNombre);
        formaPago.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formaPagoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formaPagoKeyPressed
    {//GEN-HEADEREND:event_formaPagoKeyPressed

    }//GEN-LAST:event_formaPagoKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulaArchivos.guardaC(Cliente.getCons(), "foliosC.dat");
        ManipulaArchivos.guardaCA(VtnPrincipal.c, "Clientes.dat");
        new VtnCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed

        if (txtFecha.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || formaPago.getSelectedItem() == null)
        {
            Mensajes.error(this, "Ingrese todos los datos para poder registrar");
            if (txtNombre.getText().trim().isEmpty())
            {
                txtNombre.requestFocus();
            } else if (formaPago.getSelectedItem() == null)
            {
                formaPago.requestFocus();
            } else
            {
                txtFecha.requestFocus();
            }
            return;
        }
        //String formaPagoSeleccionada = (String) formaPago.getSelectedItem();
        char formaPagoChar = 0;
        if (formaPago.getSelectedItem().equals("-Selecciona-"))
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un metodo de pago");
        } else
        {
            if (formaPago.getSelectedItem() == "Efectivo")
            {
                formaPagoChar = 'E';
            }
            if (formaPago.getSelectedItem() == "Tarjeta")
            {
                formaPagoChar = 'T';
            }
            Cliente nuevoCliente = new Cliente(
                    txtNombre.getText(),
                    formaPagoChar,
                    txtFecha.getText()
            );
            VtnPrincipal.c = Manipulacion.insertaCliente(VtnPrincipal.c, nuevoCliente);
            VtnPrincipal.tmpCliente = nuevoCliente;
            clienteRegistrado ventana = new clienteRegistrado();
            ventana.setVisible(true);
            this.setVisible(false);

            /*char formaPagoChar = 0;
        if (txtFecha.getText().trim().isEmpty())

        {
            Mensajes.error(this, "Ingrese todos los datos para poder registrar");
            if (txtNombre.getText().trim().isEmpty())
            {
                txtNombre.requestFocus();
            } else if (formaPago.getSelectedItem() == null)
            {
                formaPago.requestFocus();
            } else
            {
                txtFecha.requestFocus();
            }
            return;
        }

        if (formaPago.getSelectedItem().equals("-Selecciona-"))
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un metodo de pago");
        } else
        {
            if (formaPago.getSelectedItem() == "Efectivo")
            {
                formaPagoChar = 'E';
            }
            if (formaPago.getSelectedItem() == "Tarjeta")
            {
                formaPagoChar = 'T';
            }
            
            VtnPrincipal.c = Manipulacion.insertaCliente(VtnPrincipal.c,
                    new Cliente(txtNombre.getText(),
                            formaPagoChar,
                            txtFecha.getText()));
            VtnPrincipal.c = Manipulacion.insertaCliente(VtnPrincipal.c, nuevoCliente);
            VtnPrincipal.tmpCliente = nuevoCliente;
            clienteRegistrado ventana = new clienteRegistrado();
            ventana.setVisible(true);
            this.setVisible(false);
            
        }*/
//        if (txtFecha.getText().trim().isEmpty())
//        {
//            Mensajes.error(this, "Ingrese todos los datos para poder registrar");
//            txtFecha.requestFocus();
//            return;
//        }
//        String formaPagoSeleccionada = (String) formaPago.getSelectedItem();
//        char formaPagoChar = formaPagoSeleccionada.charAt(0);
//        VtnPrincipal.c=Manipulacion.insertaCliente(VtnPrincipal.c, 
//                new Cliente(txtNombre.getText(), formaPagoChar, txtFecha.getText()));
//        Mensajes.exito(this,"Cliente registrado correctamente \n"+Manipulacion.despC(VtnPrincipal.c, VtnPrincipal.c.length));
//        
//        btnCancelarActionPerformed(evt);
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> formaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
