/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.text.SimpleDateFormat;
import poo.ManipulaArchivos;
import poo.Manipulacion;
import poo.Socio;

/**
 *
 * @author Meche}
 */
public class VtnRegistroSocio extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRegistroSocio
     */
    public VtnRegistroSocio()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtNombre = new javax.swing.JTextField();
        txtPlacas = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JToggleButton();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        txtFechaC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de socios");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, -1));

        txtPlacas.setEnabled(false);
        txtPlacas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtPlacasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtPlacasKeyTyped(evt);
            }
        });
        getContentPane().add(txtPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, -1));

        txtModelo.setEnabled(false);
        txtModelo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtModeloActionPerformed(evt);
            }
        });
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtModeloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtModeloKeyTyped(evt);
            }
        });
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 230, -1));

        btnAceptar.setBackground(new java.awt.Color(151, 247, 185));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Aceptar.png"))); // NOI18N
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        BtnCancelar.setBackground(new java.awt.Color(255, 115, 115));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Cancelar.png"))); // NOI18N
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jdcFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jdcFechaPropertyChange(evt);
            }
        });
        jdcFecha.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jdcFechaKeyPressed(evt);
            }
        });
        getContentPane().add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 40, -1));

        txtFechaC.setEditable(false);
        txtFechaC.setEnabled(false);
        txtFechaC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFechaCActionPerformed(evt);
            }
        });
        txtFechaC.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtFechaCKeyPressed(evt);
            }
        });
        getContentPane().add(txtFechaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/RegistroSocios.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulaArchivos.guardaS(Socio.getCons(), "foliosS.dat");
        ManipulaArchivos.guardaSA(VtnPrincipal.s, "Socios.dat");
        new VtnSocio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        new VtnSocio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnCancelarActionPerformed
    {//GEN-HEADEREND:event_BtnCancelarActionPerformed
        CtrlInterfaz.limpia(txtNombre, txtPlacas, txtModelo, txtFechaC);
        CtrlInterfaz.habilita(false, txtPlacas, txtModelo, btnAceptar);
        CtrlInterfaz.selecciona(txtNombre);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyPressed
    {//GEN-HEADEREND:event_txtNombreKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, txtNombre, txtPlacas);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtPlacasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPlacasKeyPressed
    {//GEN-HEADEREND:event_txtPlacasKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, txtPlacas, txtModelo);
    }//GEN-LAST:event_txtPlacasKeyPressed

    private void txtModeloKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtModeloKeyPressed
    {//GEN-HEADEREND:event_txtModeloKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, txtModelo, btnAceptar);
    }//GEN-LAST:event_txtModeloKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNombreKeyTyped
    {//GEN-HEADEREND:event_txtNombreKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, txtNombre.getText());
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPlacasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPlacasKeyTyped
    {//GEN-HEADEREND:event_txtPlacasKeyTyped
        Validaciones.validaAlfanumerico(evt, 5, txtPlacas.getText());
    }//GEN-LAST:event_txtPlacasKeyTyped

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtModeloKeyTyped
    {//GEN-HEADEREND:event_txtModeloKeyTyped
        Validaciones.validaAlfanumerico(evt, 15, txtModelo.getText());
    }//GEN-LAST:event_txtModeloKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        if (txtFechaC.getText().trim().isEmpty())
        {
            Mensajes.error(this, "Ingrese todos los datos para poder registrar");
            txtFechaC.requestFocus();
            return;
        }
        Socio nuevoSocio = new Socio(txtNombre.getText(), txtPlacas.getText(), txtModelo.getText(), txtFechaC.getText());
        VtnPrincipal.s = Manipulacion.insertaSocio(VtnPrincipal.s, nuevoSocio);
        VtnPrincipal.tmpSocio = nuevoSocio;
        socioRegistrado ventana = new socioRegistrado();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    private void jdcFechaPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jdcFechaPropertyChange
    {//GEN-HEADEREND:event_jdcFechaPropertyChange
        /* if (evt.getOldValue() != null) //verifica que no tenga datos
        {
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            txtFechaC.setText(ff.format(jdcFecha.getCalendar().getTime()));
        } else
        {

        }*/
        if ("date".equals(evt.getPropertyName())) { // Detecta cambios en la propiedad "date"
            if (jdcFecha.getDate() != null) { // Asegúrate de que haya una fecha seleccionada
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Define el formato de fecha
                String formattedDate = dateFormat.format(jdcFecha.getDate()); // Formatea la fecha seleccionada
                txtFechaC.setText(formattedDate); // Actualiza el JTextField con la fecha
                
            }
        }
    }//GEN-LAST:event_jdcFechaPropertyChange

    private void jdcFechaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jdcFechaKeyPressed
    {//GEN-HEADEREND:event_jdcFechaKeyPressed
        //Validaciones.enterCadenaNoVacia(this, evt, jdcFecha, btnAceptar);
    }//GEN-LAST:event_jdcFechaKeyPressed

    private void txtFechaCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFechaCActionPerformed
    {//GEN-HEADEREND:event_txtFechaCActionPerformed
        
    }//GEN-LAST:event_txtFechaCActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtModeloActionPerformed
    {//GEN-HEADEREND:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtFechaCKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFechaCKeyPressed
    {//GEN-HEADEREND:event_txtFechaCKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, txtFechaC, btnAceptar);
    }//GEN-LAST:event_txtFechaCKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistroSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnCancelar;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTextField txtFechaC;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlacas;
    // End of variables declaration//GEN-END:variables
}
