/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import static Interfaz.VtnPrincipal.s;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import poo.ManipulaArchivos;
import poo.Manipulacion;
import poo.Socio;

/**
 *
 * @author Meche}
 */
public class VtnSocio extends javax.swing.JFrame
{

    public static String nS = " ", nomS = " ";
    public static int pos=0;
    

    /**
     * Creates new form VtnSocio
     */
    public VtnSocio()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCancelar = new javax.swing.JToggleButton();
        BtnRegistrarSocio = new javax.swing.JToggleButton();
        TxtNumSocio = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login socios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCancelar.setBackground(new java.awt.Color(255, 115, 115));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Cancelar.png"))); // NOI18N
        BtnCancelar.setToolTipText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        BtnRegistrarSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/BtnRegistrarsocio.png"))); // NOI18N
        BtnRegistrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarSocioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrarSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        TxtNumSocio.setToolTipText("Número de socio");
        TxtNumSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumSocioActionPerformed(evt);
            }
        });
        TxtNumSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNumSocioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumSocioKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNumSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, -1));

        btnAceptar.setBackground(new java.awt.Color(151, 247, 185));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Aceptar.png"))); // NOI18N
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAceptarKeyPressed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/LoginSocio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        new VtnPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void TxtNumSocioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TxtNumSocioActionPerformed
    {//GEN-HEADEREND:event_TxtNumSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumSocioActionPerformed

    private void TxtNumSocioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TxtNumSocioKeyPressed
    {//GEN-HEADEREND:event_TxtNumSocioKeyPressed
        Validaciones.enterEntero(this, evt, TxtNumSocio, btnAceptar);
    }//GEN-LAST:event_TxtNumSocioKeyPressed

    private void TxtNumSocioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_TxtNumSocioKeyTyped
    {//GEN-HEADEREND:event_TxtNumSocioKeyTyped
        Validaciones.validaEntero(evt, 5, TxtNumSocio.getText());
    }//GEN-LAST:event_TxtNumSocioKeyTyped

    private void BtnRegistrarSocioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnRegistrarSocioActionPerformed
    {//GEN-HEADEREND:event_BtnRegistrarSocioActionPerformed
        VtnRegistroSocio abrirVtn = new VtnRegistroSocio();
        abrirVtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegistrarSocioActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnCancelarActionPerformed
    {//GEN-HEADEREND:event_BtnCancelarActionPerformed
        CtrlInterfaz.limpia(TxtNumSocio);
        CtrlInterfaz.habilita(false, btnAceptar);
        CtrlInterfaz.selecciona(TxtNumSocio);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        nS = TxtNumSocio.getText();
        nomS = Manipulacion.buscarSocioNom(VtnPrincipal.s, Manipulacion.buscarSocio(VtnPrincipal.s, nS));
        pos=Integer.parseInt(nS);
        if (nomS == "nul")
        {
            Mensajes.exito(this, "usuario no encontrado");
        } else
        {
            new VtnSocioDashboard().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar()== '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        s = (Socio[]) ManipulaArchivos.cargaAS("Socios.dat");
        try
        {
            Socio.setCons((int) ManipulaArchivos.cargaS("foliosS.dat"));
        } catch (Exception e)
        {
            Socio.setCons(0);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnCancelar;
    private javax.swing.JToggleButton BtnRegistrarSocio;
    private javax.swing.JTextField TxtNumSocio;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
