/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import static Interfaz.VtnPrincipal.v;
import static Interfaz.VtnPrincipal.vC;
import cjb.ci.Mensajes;
import poo.ManipulaArchivos;
import poo.Manipulacion;
import poo.Viaje;

/**
 *
 * @author Meche}
 */
public class VtnSocioDashboard extends javax.swing.JFrame
{

    /**
     * Creates new form VtnSocioRegistrado
     */
    public VtnSocioDashboard()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnModificaDatos = new javax.swing.JToggleButton();
        btnIniciarViaje = new javax.swing.JToggleButton();
        btnCancelaViaje = new javax.swing.JToggleButton();
        btnTerminarViaje = new javax.swing.JToggleButton();
        btnConsultaViajes = new javax.swing.JToggleButton();
        btnConsultaGanancias = new javax.swing.JToggleButton();
        BtnSalir = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard socios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificaDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/SocioModificaDatos.png"))); // NOI18N
        btnModificaDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificaDatos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnModificaDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificaDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btnIniciarViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/SocioIniciaViaje.png"))); // NOI18N
        btnIniciarViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarViaje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIniciarViajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        btnCancelaViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/SocioCancelaViaje.png"))); // NOI18N
        btnCancelaViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelaViaje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelaViajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        btnTerminarViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/SocioTerminaViaje.png"))); // NOI18N
        btnTerminarViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminarViaje.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTerminarViajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerminarViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        btnConsultaViajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/SocioConsultaViajes.png"))); // NOI18N
        btnConsultaViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaViajes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConsultaViajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        btnConsultaGanancias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/ClientesConsultaGastos.png"))); // NOI18N
        btnConsultaGanancias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaGanancias.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConsultaGananciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaGanancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/Salir2.png"))); // NOI18N
        BtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/DashboardSocio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificaDatosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnModificaDatosActionPerformed
    {//GEN-HEADEREND:event_btnModificaDatosActionPerformed
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.vC, "ViajesC.dat");
        vtnSocioModificaDatos vtn = new vtnSocioModificaDatos();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModificaDatosActionPerformed

    private void btnConsultaViajesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConsultaViajesActionPerformed
    {//GEN-HEADEREND:event_btnConsultaViajesActionPerformed
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.vC, "ViajesC.dat");
        vtnSocioConsultaViajes vtn = new vtnSocioConsultaViajes();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaViajesActionPerformed

    private void btnConsultaGananciasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConsultaGananciasActionPerformed
    {//GEN-HEADEREND:event_btnConsultaGananciasActionPerformed
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.vC, "ViajesC.dat");
        vtnSocioConsultaGanancias vtn = new vtnSocioConsultaGanancias();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaGananciasActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnSalirActionPerformed
    {//GEN-HEADEREND:event_BtnSalirActionPerformed
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.vC, "ViajesC.dat");
        VtnPrincipal vtn = new VtnPrincipal();
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void btnIniciarViajeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIniciarViajeActionPerformed
    {//GEN-HEADEREND:event_btnIniciarViajeActionPerformed
        int y = 0;
        if (VtnPrincipal.v == null || VtnPrincipal.s == null || VtnSocio.pos < 0 || VtnSocio.pos > VtnPrincipal.v.length)
        {
            Mensajes.error(this, "No hay viajes por Iniciar");
        } else
        {
            if (VtnPrincipal.v[VtnSocio.pos - 1] == null)
            {
                Mensajes.error(this, "No hay viajes por Iniciar");
            } else
            {
                for (int j = 0; j < VtnPrincipal.v[VtnSocio.pos - 1].length; j++)
                {
                    if (VtnPrincipal.v[VtnSocio.pos - 1][j].getStatus() == 'E')
                    {
                        VtnPrincipal.v = Manipulacion.iniciarViajeS(VtnPrincipal.s, VtnPrincipal.v, VtnSocio.pos);
                        int f= Integer.parseInt(VtnPrincipal.v[VtnSocio.pos - 1][j].getFolioCliente());
                        VtnPrincipal.vC = Manipulacion.iniciarViajeS(VtnPrincipal.s, VtnPrincipal.vC, f);
                        Mensajes.exito(this, "Viaje iniciado");
                        y = 1;
                    }
                }
                if (y == 0)
                {
                    Mensajes.error(this, "No hay viaje por Iniciar");
                }
            }
        }
    }//GEN-LAST:event_btnIniciarViajeActionPerformed

    private void btnCancelaViajeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelaViajeActionPerformed
    {//GEN-HEADEREND:event_btnCancelaViajeActionPerformed
        int y = 0;
        if (VtnPrincipal.v == null || VtnPrincipal.s == null || VtnSocio.pos < 0 || VtnSocio.pos > VtnPrincipal.v.length)
        {
            Mensajes.error(this, "No hay viajes por cancelar");

        } else
        {
            if (VtnPrincipal.v[VtnSocio.pos - 1] == null)
            {
                Mensajes.exito(this, "No hay viajes por cancelar");
            } else
            {

                for (int j = 0; j < VtnPrincipal.v[VtnSocio.pos - 1].length; j++)
                {
                    if (VtnPrincipal.v[VtnSocio.pos - 1][j].getStatus() == 'E' || VtnPrincipal.v[VtnSocio.pos - 1][j].getStatus() == 'S')
                    {
                        VtnPrincipal.v = Manipulacion.cancelarViajeS(VtnPrincipal.s, VtnPrincipal.v, VtnSocio.pos);
                        VtnPrincipal.vC = Manipulacion.cancelarViaje(VtnPrincipal.s, VtnPrincipal.vC, Manipulacion.buscarStatusE(VtnPrincipal.vC, VtnPrincipal.s, VtnPrincipal.v[VtnSocio.pos - 1][j].getFolioCliente()));
                        Mensajes.exito(this, "Viaje cancelado");
                        y = 1;
                    }
                }
                if (y == 0)
                {
                    Mensajes.exito(this, "No hay viaje por cancelar");
                }
            }
        }
    }//GEN-LAST:event_btnCancelaViajeActionPerformed

    private void btnTerminarViajeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTerminarViajeActionPerformed
    {//GEN-HEADEREND:event_btnTerminarViajeActionPerformed
        int y = 0;
        if (VtnPrincipal.v == null || VtnPrincipal.s == null || VtnSocio.pos < 0 || VtnSocio.pos > VtnPrincipal.v.length)
        {
            Mensajes.error(this, "No hay viajes por terminar");
        } else
        {
            if (VtnPrincipal.v[VtnSocio.pos - 1] == null)
            {
                Mensajes.error(this, "No hay viajes por terminar");
            } else
            {
                for (int j = 0; j < VtnPrincipal.v[VtnSocio.pos - 1].length; j++)
                {
                    if (VtnPrincipal.v[VtnSocio.pos - 1][j].getStatus() == 'I')
                    {
                        VtnPrincipal.v = Manipulacion.terminarViajeS(VtnPrincipal.s, VtnPrincipal.v, VtnSocio.pos);
                        int f= Integer.parseInt(VtnPrincipal.v[VtnSocio.pos - 1][j].getFolioCliente());
                        VtnPrincipal.vC = Manipulacion.terminarViajeS(VtnPrincipal.s, VtnPrincipal.vC, f);
                        
                        Mensajes.exito(this, "Viaje terminado");
                        y = 1;
                    }
                }
                if (y == 0)
                {
                    Mensajes.exito(this, "no hay Viaje por terminar");
                }
            }
        }
    }//GEN-LAST:event_btnTerminarViajeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVA(VtnPrincipal.vC, "ViajesC.dat");
        new VtnPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        v = (Viaje[][]) ManipulaArchivos.cargaAV("Viajes.dat");
        vC = (Viaje[][]) ManipulaArchivos.cargaAVC("ViajesC.dat");
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnSocioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnSocioDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnSalir;
    private javax.swing.JToggleButton btnCancelaViaje;
    private javax.swing.JToggleButton btnConsultaGanancias;
    private javax.swing.JToggleButton btnConsultaViajes;
    private javax.swing.JToggleButton btnIniciarViaje;
    private javax.swing.JToggleButton btnModificaDatos;
    private javax.swing.JToggleButton btnTerminarViaje;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
