/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import cjb.ci.Mensajes;
import poo.ManipulaArchivos;
import poo.Manipulacion;
import poo.Viaje;

/**
 *
 * @author Meche}
 */
public class vtnViajeCreado extends javax.swing.JFrame
{

    /**
     * Creates new form vtnViajeCreado
     */
    public vtnViajeCreado()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtOrigen = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtEstatus = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Viaje creado");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOrigen.setEnabled(false);
        getContentPane().add(txtOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, -1));

        txtDestino.setEnabled(false);
        getContentPane().add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, -1));

        txtFecha.setEnabled(false);
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, -1));

        txtEstatus.setEnabled(false);
        getContentPane().add(txtEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 220, -1));

        txtMonto.setEnabled(false);
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/imagenes/ViajeCreado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        if (VtnPrincipal.tmpVC != null)
        {
            if (VtnPrincipal.tmpVC != null)
            {
                txtOrigen.setText(VtnPrincipal.tmpVC.getOrigen());
                txtDestino.setText(VtnPrincipal.tmpVC.getDestino());
                txtFecha.setText(VtnPrincipal.tmpVC.getFecha());
                txtMonto.setText(String.valueOf(VtnPrincipal.tmpVC.getMonto()));

                char status = VtnPrincipal.tmpVC.getStatus();
                if (status == 'E')
                {
                    txtEstatus.setText("En espera");
                } else if (status == 'S')
                {
                    txtEstatus.setText("Sin socio asignado");
                }
            } else
            {
                Mensajes.error(this, "Aun no se registran viajes");
            }

        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        ManipulaArchivos.guardaVA(VtnPrincipal.v, "Viajes.dat");
        ManipulaArchivos.guardaVAC(VtnPrincipal.vC, "ViajesC.dat");
        VtnClienteDashboard vtn = new VtnClienteDashboard(); 
        vtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnViajeCreado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnViajeCreado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnViajeCreado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnViajeCreado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnViajeCreado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
